### ISSUE TITLE
Add New Translation Engines

### ISSUE THREAD

**Issue by ValenokPC** [YiiGuxing/TranslationPlugin#1519] opened 2022-05-17 19:20 UTC
### Preflight Checklist
*Please ensure you've completed the following steps by replacing `[ ]` with `[x]`*

* [x] I have read the [README](https://github.com/YiiGuxing/TranslationPlugin), but still can't solve my problem.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Proposed Solution
Add another translation service. (Yandex Translate)

### Additional Information
https://translate.yandex.com/
https://cloud.yandex.com/services/translate

**Comment by YiiGuxing** [comment] 2022-05-18 00:42
Duplicate of #1395.

**Closed by YiiGuxing** 2022-05-18 00:42 UTC
Labels: duplicate, feature request :sparkles:
