### ISSUE TITLE
翻译文档失败

### ISSUE THREAD

**Issue by SunYangEdo** [YiiGuxing/TranslationPlugin#1326] opened 2022-04-19 12:09 UTC
翻译文档失败

**Comment by lleiwang** [comment] 2022-04-19 12:18
我今天遇到了一样的问题。

Version 3.3 Google翻译 报错 "翻译文档失败"

尝试降低 Translation 版本至 V3.2
报错：
```
翻译文档失败: 翻译失败: 解析错误

>Plugin v3.2.0.1  
>IntelliJ IDEA 2021.3.2  
>内部版本号 #IU-213.6777.52，January 28, 2022 构建  
>运行时版本: 11.0.13+7-b1751.25 aarch64  
>VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.  
>OS: macOS 12.2

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 解析错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:158)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:124)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:62)
	... 10 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:405)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:393)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 20 more
```

```

**Comment by ajian2002** [comment] 2022-04-19 13:04
+1

**Comment by zhaokun0914** [comment] 2022-04-19 13:27
+1

**Comment by QinminShen** [comment] 2022-04-19 13:42
+1 
先使用reader模式，选择翻译应急吧

**Comment by twosom** [comment] 2022-04-19 14:07
+1

**Comment by QQQ-tt** [comment] 2022-04-19 14:31
同样Google翻译文档未知错误

**Comment by ChunzhiAoe** [comment] 2022-04-20 01:12
谷歌翻译错误，试了一下百度的可以用

**Comment by StormFeng** [comment] 2022-04-20 01:24
+1

**Comment by zhaozuo** [comment] 2022-04-20 01:27
翻译文档失败：未知错误。
我也是用的谷歌翻译

**Comment by jyp-qiyu** [comment] 2022-04-20 01:31
+1,谷歌翻译一直提示未知错误

**Comment by gppwin** [comment] 2022-04-20 01:39
最新版插件 依旧有问题,idea 用的当前最新的 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/24806380/164129671-2e32a734-853b-4f03-878f-f715f96a0d14.png">

**Comment by YiiGuxing** [comment] 2022-04-20 01:48
> 最新版插件 依旧有问题,idea 用的当前最新的 <img alt="image" width="352" src="https://user-images.githubusercontent.com/24806380/164129671-2e32a734-853b-4f03-878f-f715f96a0d14.png">

@gppwin 请在IDE内部进行更新，如果没有收到推送，请手动检查更新：`Help -> Check for Updates...`

**Comment by YiiGuxing** [comment] 2022-04-20 01:50
Duplicate of #1318

**Closed** 2022-04-20 01:49 UTC
Labels: bug :bug:, duplicate, published :rocket:, fixed :hammer:

**Comment by YiiGuxing** [comment] 2022-04-20 01:51
兄弟们，问题修复版本已经发布，请在IDE内部进行更新，如果没有收到推送，请手动检查更新：`Help -> Check for Updates...`
