### ISSUE TITLE
[Auto Generated]Plugin error occurred: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access...

### ISSUE THREAD

**Issue by kulihaEvgn** [YiiGuxing/TranslationPlugin#6210] opened 2024-10-21 15:02 UTC
:warning:_`[Auto Generated Report]-=2808DBCFB65981C5029F5E9A6099DC7E=-`_

## Description

Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction ; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#46,AWT-EventQueue-0,6,main] 913593076 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)

## Environments
> **Plugin version: 3.6.6**

WebStorm 2024.3 EAP
Build #WS-243.19420.26, built on October 9, 2024
Runtime version: 21.0.4+8-b620.4 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Operating system: Windows 11.0
Last action id: SaveAll

## Stack Trace
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction ; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#46,AWT-EventQueue-0,6,main] 913593076 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:920)
	at com.intellij.openapi.editor.impl.CaretImpl.getOffset(CaretImpl.java:661)
	at com.intellij.openapi.editor.impl.CaretImpl.updateCachedState(CaretImpl.java:1463)
	at com.intellij.openapi.editor.impl.CaretImpl.updateCachedStateIfNeeded(CaretImpl.java:1457)
	at com.intellij.openapi.editor.impl.CaretImpl.updateVisualPosition(CaretImpl.java:687)
	at com.intellij.openapi.editor.impl.CaretModelImpl.updateVisualPosition(CaretModelImpl.java:122)
	at com.intellij.openapi.editor.impl.EditorImpl$4.recalculationEnds(EditorImpl.java:541)
	at com.intellij.openapi.editor.impl.SoftWrapModelImpl$1.recalculationEnds(SoftWrapModelImpl.java:119)
	at com.intellij.openapi.editor.impl.softwrap.mapping.SoftWrapApplianceManager.onRecalculationEnd(SoftWrapApplianceManager.java:208)
	at com.intellij.openapi.editor.impl.softwrap.mapping.SoftWrapApplianceManager.recalculateSoftWraps(SoftWrapApplianceManager.java:200)
	at com.intellij.openapi.editor.impl.softwrap.mapping.SoftWrapApplianceManager.recalculateIfNecessary(SoftWrapApplianceManager.java:326)
	at com.intellij.openapi.editor.impl.SoftWrapModelImpl.recalculate(SoftWrapModelImpl.java:609)
	at com.intellij.openapi.editor.impl.SoftWrapModelImpl.onBulkDocumentUpdateFinished(SoftWrapModelImpl.java:511)
	at com.intellij.openapi.editor.impl.EditorImpl.bulkUpdateFinished(EditorImpl.java:1768)
	at com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter.bulkUpdateFinished(EditorImpl.java:5504)
	at com.intellij.openapi.editor.impl.DocumentImpl.notifyListenersOnBulkModeFinished(DocumentImpl.java:1175)
	at com.intellij.openapi.editor.impl.DocumentImpl.setInBulkUpdate(DocumentImpl.java:1147)
	at com.intellij.util.DocumentUtil.executeInBulk(DocumentUtil.java:38)
	at com.intellij.util.DocumentUtil.executeInBulk(DocumentUtil.java:43)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputController.updateBlock(TerminalOutputController.kt:460)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputController.doUpdateCommandOutput(TerminalOutputController.kt:291)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputController.updateCommandOutput$lambda$10(TerminalOutputController.kt:276)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputController.doWithScrollingAware(TerminalOutputController.kt:372)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputController.updateCommandOutput(TerminalOutputController.kt:275)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputController.access$updateCommandOutput(TerminalOutputController.kt:39)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputController$RunningCommandInteractivity.setupContentUpdating$lambda$1(TerminalOutputController.kt:430)
	at org.jetbrains.plugins.terminal.block.output.TerminalOutputContentUpdatesScheduler$scheduleChangeApplying$1.invokeSuspend(TerminalOutputContentUpdatesScheduler.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:221)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:679)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:574)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1058)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1058)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:350)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:396)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.kt:716)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$4(ProgressWindow.java:228)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runUnlockingIntendedWrite(AnyThreadWriteThreadingSupport.kt:195)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:847)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$5(ProgressWindow.java:223)
	at com.intellij.openapi.progress.util.ProgressWindow.executeInModalContext(ProgressWindow.java:204)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:221)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$execFromEDT$7(ProgressRunner.java:315)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214)
	at com.intellij.openapi.progress.impl.ProgressRunner.execFromEDT(ProgressRunner.java:312)
	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:381)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:307)
	at cn.yiiguxing.plugin.translate.diagnostic.github.auth.GitHubDeviceAuthTask.queueAndGet(GitHubDeviceAuthTask.kt:77)
	at cn.yiiguxing.plugin.translate.diagnostic.github.TranslationGitHubAppService.authorize(TranslationGitHubAppService.kt:49)
	at cn.yiiguxing.plugin.translate.diagnostic.github.TranslationGitHubAppService.auth(TranslationGitHubAppService.kt:31)
	at cn.yiiguxing.plugin.translate.diagnostic.ReportSubmitter.requestNewCredentials(ReportSubmitter.kt:86)
	at cn.yiiguxing.plugin.translate.diagnostic.ReportSubmitter.changeReporterAccount(ReportSubmitter.kt:81)
	at cn.yiiguxing.plugin.translate.diagnostic.ReportSubmitter$onError$$inlined$invokeLater$default$1.run(Applications.kt:178)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:176)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:87)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:841)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:420)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:679)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:574)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1049)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:915)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1049)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1058)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1058)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:350)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:396)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by YiiGuxing** [comment] 2024-10-22 08:14
Duplicate of #6206

**Closed by YiiGuxing** 2024-10-22 08:14 UTC
Labels: duplicate, bug/crash 💥, auto generated report 🤖
