### ISSUE TITLE
有道翻译提示参数错误

### ISSUE THREAD

**Issue by MrR0990** [YiiGuxing/TranslationPlugin#4758] opened 2023-11-15 01:15 UTC
### 📝 Issue Description

有道翻译提示参数错误
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10650866/d5a19352-314f-49fb-98cb-2e1c4ca0a642)

### 🏷 Plugin Version

最新

### 🔁 Translation Engine(s)

Youdao Translate

### 💻 IDE and Operating Environment

```plain text
AndroidStudio
```

### 📋 Stacktrace

```plain text
有道翻译提示参数错误
```

**Comment by YiiGuxing** [comment] 2023-11-15 06:35
Duplicate of #4739

**Closed by YiiGuxing** 2023-11-15 06:35 UTC
Labels: bug 🐛, duplicate
